### ISSUE TITLE
eclim freezes by auto-save-file

### ISSUE THREAD

**Issue by tsukimizake** [senny/emacs-eclim#276] opened 2016-05-02 00:23 UTC
emacs-eclim freezes when emacs generates auto-save-file, such as `#Main.java#`.
`(setq auto-save-default nil)` solved it.

**Comment by sandric** [comment] 2016-07-25 08:45
Yes, I experience the same.

**Comment by jachaf6746** [comment] 2016-10-20 20:40
I have this problem as well. I will give that snippet a try.

**Comment by mwillsey** [comment] 2016-10-20 22:50
Same, this workout worked for me.

**Comment by squarepegsys** [comment] 2017-04-13 15:04
Same here, fwiw

**Comment by nloyola** [comment] 2017-04-13 15:40
Development of this package moved to [emacs-eclim/emacs-eclim](https://github.com/emacs-eclim/emacs-eclim). Are you using the version published by that repository?

**Comment by squarepegsys** [comment] 2017-04-13 15:44
I had the problem and Google brought me here. :) I didn't realize that I was in the wrong github.
And I installed it from MELPA, so I assume it's the official one (not yours)

**Comment by nloyola** [comment] 2017-04-13 15:46
What is the version number on the package you downloaded?

**Comment by squarepegsys** [comment] 2017-04-13 15:59
it's `eclim-20170328.1807`

**Comment by nloyola** [comment] 2017-04-30 18:43
I cannot reproduce this error with Emacs 25.2.1 on Ubuntu 17.04 and Eclim version 20170328.1807.

What version of Emacs? What operating system are you running? Please reply to these questions in the issue in the new repository at: emacs-eclim/emacs-eclim#56.

**Comment by nloyola** [comment] 2017-05-01 02:07
I committed change emacs-eclim/emacs-eclim@1d0ac3f that may fix this issue. The package will be updated to Melpa soon. Please let me know if it fixes your problem.

**Closed** 2023-04-17 01:20 UTC
